### ISSUE TITLE
Open Source PennAI discussion ticket

### ISSUE THREAD

**Issue by hjwilli** [EpistasisLab/Aliro#124]
Ticket for keeping track of overall discussion/issues about the 'Open Source PennAI' milestone.
---
**basic user and developer documentation**
- [ ] User docs point to an intro to ML, particularly to dataset preprocessing primer/best practices on how to prepare a dataset
- [ ] ~ Update API documentation in the api.raml file
- [ ] Basic architecture documentation

**able to install/setup easily**
- [x] Create production docker images (refactoring paths in docker files, create production docker files that copy instead of mount local volumes, create docker-compose file to build prod images)
- [ ] Host production images in github
- [ ] Docs to run from production images

**User able to run from docs/basic operation**
- [ ] ! UI for dataset upload (#121, #119)
- [x] ! dataset refactoring (#59)
- [x] fix restart bug (can restart and retain state)
- [x] make sure ai engine restarts if failed
- [x] multiple machines
- [ ] handle larger datasets, or gracefully not handle larger datasets
- [x] ! ordinal and catagorical feature support (#121)
- [x] ! machine timeout (variable, probably through the config file) (#123)
- [ ] x tunning parameters for a dataset/algorithm (grid search)
- [ ] ~ charts for dataset profiles page
- [ ] ~ charts for results page
- [x] ~ knowledgebase restart?
- [ ] ~ cloud start 
- [ ] ~ decision tree representation of the model on the results page (#131)

**user able to rerun recommender experiments?**
- [x] ! decide default recommender
- [x] decide default recommender settings/terminal conditions
- [ ] users recommender request can use a specific terminal condition
- [ ] ! additionial terminal conditions (stall count?) (#126)
- [ ] ! recommender expected result for an experiment stored and can be retrieved via api
- [ ] ~ UI - progress bar for recommender status
- [ ] ~ multiple recommenders
- [ ] ~ [lime?](https://github.com/marcotcr/lime) - a python library for use of explaining models, could be used on the results page
- [x] ~ [surprise?](http://surpriselib.com/) - a python library for building and analyzing recommender systems, could be used in conjuction with the recommender engine
- [ ] ~ new UI page for knowledgebase and ai recommender status

**AI Recommenders Paper**

**Knowledgebases** 
- [ ] able to export knowledgebase
- [x] able to import knowledgebase
- [ ] ~ able to import multiple knowledgebases

**able to add new recommenders**
- [x] user documentation on how to create and use recommender
- [x] python template

**able to add define new ml algorithms**
- [ ] docs for projects.json

**choose a license**
- [x] Licences of existing components (fglabs, scikit-learn, datasets) (#125)
- [x] Evaluate licenses (#125)

**public github site**
- [ ] Travis CI
- [ ] ~ Github site?
- [ ] Doc generation with something like makedoc, readthedoc

(~ denotes non-critical or future feature ideas)
