### ISSUE TITLE
Sharon's To-Do

### ISSUE THREAD

**Issue by Coder-Sharon** [EpistasisLab/Aliro#70]
### Tasks before demo
- [x] Comment out "Add new dataset" button
- [x] Move admin page button to main navbar
- [x] On the admin page, keep the status icon grey until pinging is fixed, and add hover text as "Unknown"
- [x] On the experiments page, change count text from "results" to "experiments"
- [x] On datasets page, change text from "n results" to "n completed experiments"
- [x] "Completed" should encompass 3 categories (fail, cancelled, and success)
- [x] If no results in category such as "pending", display message that nothing matches that filter rather than defaulting to "all" (essentially, count on datasets page should always match count on experiments page for a given category)
- [x] Make the dataset details page "Under Construction" rather than 404
- [x] Add ellipses to long dataset names, with full name available on hover
- [x] Provide message on builder page if user submits experiment and an error or a message like "no machine capacity" occurs
- [x] Make sure dropdown is disabled for cancelled/failed experiments
- [x] ~Set admin modal windows to top~
- [x] ~Fix AI toggle button states ('on' -> 'queuing' -> 'finished')~

### Tasks for next week
- [x] Divide lab and web_app (nest in lab directory, do in separate branch)
- [x] Add algorithm description to builder page when available in json
- [x] Fix resizing issue for dataset cards
- [x] Use local Semantic UI css rather than cdn
- [x] Add rows/cols to datasets page on dataset name hover (after metadata works)
- [x] Add number of classes to dataset name hover
- [x] Dataset details page (n_cols, n_rows, n_classes on top, empty fields on bottom with N/A)
- [x] Add algorithm sklearn link to popup
- [x] Investigate IE issue with Webpack/Babel (at the very least document and make ticket, link to commit where webpack change was made)
- [x] ~Possibly remove SceneHeader component~
- [x] Send json ideas document

### Incomplete tasks
- [x] Show "No machine capacity" from json for error
- [x] Change to use choices/values lists for param options: https://github.com/EpistasisLab/pennai/issues/79#issuecomment-418496550
- [ ] Get status icons for machines to work with pinging
- [ ] Fix action dropdown when table is horizantally scrollable (or change to icon buttons)
- [ ] Dynamic charts
